version: "3.9"

services:
  database:
    image: postgres:16-alpine
    container_name: database_dev
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=supersecret_dev
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "appuser", "-d", "appdb"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - appnet

  backend:
    image: node:lts-alpine
    container_name: backend_dev
    working_dir: /usr/src/app
    command: >
      sh -c "
        npm ci &&
        npm run db:migrate &&
        npm run dev
      "
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      - DATABASE_URL=postgres://appuser:supersecret_dev@database:5432/appdb
      - PORT=3000
    depends_on:
      - database
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  dbdata:
